// <auto-generated />
using System;
using MezunBurada.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MezunBurada.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260817205003_AddReviewIsFeatured")]
    partial class AddReviewIsFeatured
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MezunBurada.Web.Models.CareerPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubFieldId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubFieldId");

                    b.ToTable("CareerPaths");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.CareerPathSkill", b =>
                {
                    b.Property<int>("CareerPathId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.HasKey("CareerPathId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CareerPathSkills");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ChallengingFor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DegreeType")
                        .HasColumnType("integer");

                    b.Property<int>("EducationDurationYears")
                        .HasColumnType("integer");

                    b.Property<int>("ExamType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MainTopics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuitableFor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.DepartmentSkill", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("DepartmentId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("DepartmentSkills");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Faq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Faqs");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.InterestQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("InterestQuestions");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.InterestQuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestQuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("MapsToSubFieldId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InterestQuestionId");

                    b.HasIndex("MapsToSubFieldId");

                    b.ToTable("InterestQuestionOptions");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.JobRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerPathId")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CareerPathId");

                    b.ToTable("JobRoles");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.LevelQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("SubFieldId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("SubFieldId");

                    b.ToTable("LevelQuestions");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.LevelQuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelQuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LevelQuestionId");

                    b.ToTable("LevelQuestionOptions");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.MarketDemandSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerPathId")
                        .HasColumnType("integer");

                    b.Property<string>("DemandNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CareerPathId");

                    b.ToTable("MarketDemandSkills");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExpertiseAreaId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpertiseAreaId");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.MentorSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MentorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("UserId");

                    b.ToTable("MentorSessions");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerPathId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstimatedDuration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CareerPathId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("SubFieldId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SubFieldId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Roadmap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerPathId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CareerPathId");

                    b.ToTable("Roadmaps");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.RoadmapStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstimatedDuration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HowToApproach")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("PrerequisiteStepId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("integer");

                    b.Property<int>("RoadmapId")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int?>("SuggestedProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrerequisiteStepId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("RoadmapId");

                    b.HasIndex("SkillId");

                    b.HasIndex("SuggestedProjectId");

                    b.ToTable("RoadmapSteps");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.SubField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExamplePositions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommendedTechnologies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartingTopics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("SubFields");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerMatchPercent")
                        .HasColumnType("integer");

                    b.Property<int?>("CareerPathId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("SubFieldId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CareerPathId");

                    b.HasIndex("SubFieldId");

                    b.HasIndex("UserId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.CareerPath", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.SubField", "SubField")
                        .WithMany("CareerPaths")
                        .HasForeignKey("SubFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubField");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.CareerPathSkill", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.CareerPath", "CareerPath")
                        .WithMany("CareerPathSkills")
                        .HasForeignKey("CareerPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MezunBurada.Web.Models.Skill", "Skill")
                        .WithMany("CareerPathSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CareerPath");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Department", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.Category", "Category")
                        .WithMany("Departments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.DepartmentSkill", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.Department", "Department")
                        .WithMany("DepartmentSkills")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MezunBurada.Web.Models.Skill", "Skill")
                        .WithMany("DepartmentSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Faq", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.Department", "Department")
                        .WithMany("Faqs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.InterestQuestion", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.Department", "Department")
                        .WithMany("InterestQuestions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.InterestQuestionOption", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.InterestQuestion", "InterestQuestion")
                        .WithMany("Options")
                        .HasForeignKey("InterestQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MezunBurada.Web.Models.SubField", "MapsToSubField")
                        .WithMany("InterestQuestionOptions")
                        .HasForeignKey("MapsToSubFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InterestQuestion");

                    b.Navigation("MapsToSubField");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.JobRole", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.CareerPath", "CareerPath")
                        .WithMany("JobRoles")
                        .HasForeignKey("CareerPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerPath");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.LevelQuestion", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MezunBurada.Web.Models.SubField", "SubField")
                        .WithMany("LevelQuestions")
                        .HasForeignKey("SubFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("SubField");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.LevelQuestionOption", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.LevelQuestion", "LevelQuestion")
                        .WithMany("Options")
                        .HasForeignKey("LevelQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LevelQuestion");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.MarketDemandSkill", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.CareerPath", "CareerPath")
                        .WithMany("MarketDemandSkills")
                        .HasForeignKey("CareerPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerPath");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Mentor", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.CareerPath", "ExpertiseArea")
                        .WithMany("Mentors")
                        .HasForeignKey("ExpertiseAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpertiseArea");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.MentorSession", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.Mentor", "Mentor")
                        .WithMany("Sessions")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MezunBurada.Web.Models.User", "User")
                        .WithMany("MentorSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Project", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.CareerPath", "CareerPath")
                        .WithMany("Projects")
                        .HasForeignKey("CareerPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerPath");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Review", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MezunBurada.Web.Models.SubField", "SubField")
                        .WithMany()
                        .HasForeignKey("SubFieldId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("SubField");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Roadmap", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.CareerPath", "CareerPath")
                        .WithMany("Roadmaps")
                        .HasForeignKey("CareerPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerPath");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.RoadmapStep", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.RoadmapStep", "PrerequisiteStep")
                        .WithMany()
                        .HasForeignKey("PrerequisiteStepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MezunBurada.Web.Models.Resource", "Resource")
                        .WithMany("RoadmapSteps")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MezunBurada.Web.Models.Roadmap", "Roadmap")
                        .WithMany("Steps")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MezunBurada.Web.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MezunBurada.Web.Models.Project", "SuggestedProject")
                        .WithMany("SuggestedForSteps")
                        .HasForeignKey("SuggestedProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrerequisiteStep");

                    b.Navigation("Resource");

                    b.Navigation("Roadmap");

                    b.Navigation("Skill");

                    b.Navigation("SuggestedProject");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.SubField", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.Department", "Department")
                        .WithMany("SubFields")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.TestResult", b =>
                {
                    b.HasOne("MezunBurada.Web.Models.CareerPath", "CareerPath")
                        .WithMany()
                        .HasForeignKey("CareerPathId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MezunBurada.Web.Models.SubField", "SubField")
                        .WithMany()
                        .HasForeignKey("SubFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MezunBurada.Web.Models.User", "User")
                        .WithMany("TestResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerPath");

                    b.Navigation("SubField");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.CareerPath", b =>
                {
                    b.Navigation("CareerPathSkills");

                    b.Navigation("JobRoles");

                    b.Navigation("MarketDemandSkills");

                    b.Navigation("Mentors");

                    b.Navigation("Projects");

                    b.Navigation("Roadmaps");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Category", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Department", b =>
                {
                    b.Navigation("DepartmentSkills");

                    b.Navigation("Faqs");

                    b.Navigation("InterestQuestions");

                    b.Navigation("SubFields");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.InterestQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.LevelQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Mentor", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Project", b =>
                {
                    b.Navigation("SuggestedForSteps");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Resource", b =>
                {
                    b.Navigation("RoadmapSteps");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Roadmap", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.Skill", b =>
                {
                    b.Navigation("CareerPathSkills");

                    b.Navigation("DepartmentSkills");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.SubField", b =>
                {
                    b.Navigation("CareerPaths");

                    b.Navigation("InterestQuestionOptions");

                    b.Navigation("LevelQuestions");
                });

            modelBuilder.Entity("MezunBurada.Web.Models.User", b =>
                {
                    b.Navigation("MentorSessions");

                    b.Navigation("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
